language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.1.300
branches:
  only:
    - master
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/dotnet-build.sh
notifications:
  email:
    on_success: never
    on_failure: always
