language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.1.300
env:
  global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
script:
  - dotnet build
  - cd ./src/Zek.Shared
  - dotnet pack -c Release --version-suffix $TRAVIS_BUILD_NUMBER -o dist
  - dotnet nuget push ./dist/*.nupkg -k $NUGET_API_KEY -s $NUGET_SOURCE